### ISSUE TITLE
New release '20.04.1 LTS' available. Run 'do-release-upgrade' to upgrade to it.

### ISSUE THREAD

**Issue by Phi-Ho** [MiSTer-devel/mr-fusion#10]
Hello,

ubuntu-bionic was just restarted and these messages were displayed:
 
....
,,,
==> default: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> default: available! You currently have version '20210106.0.0'. The latest is version
==> default: '20210107.0.0'. Run `vagrant box update` to update.
...
...
New release '20.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

*** System restart required ***

Please find the full transcript appended below.

Should 'do-release-upgrade'  be run, should the system be restarted?

Regards,

phiho

PS C:\FPGA\mr-fusion> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20210106.0.0' is up to date...
==> default: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> default: available! You currently have version '20210106.0.0'. The latest is version
==> default: '20210107.0.0'. Run `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions 6.1.16 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/FPGA/mr-fusion
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
PS C:\FPGA\mr-fusion> vagrant ssh
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-129-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Jan  8 18:44:39 UTC 2021

  System load:  0.02               Processes:             146
  Usage of /:   22.1% of 48.41GB   Users logged in:       0
  Memory usage: 3%                 IP address for enp0s3: 10.0.2.15
  Swap usage:   0%

 * Introducing self-healing high availability clusters in MicroK8s.
   Simple, hardened, Kubernetes for production, from RaspberryPi to DC.

     https://microk8s.io/high-availability

0 packages can be updated.
0 of these updates are security updates.

New release '20.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

*** System restart required ***
Last login: Thu Jan  7 22:10:31 2021 from 10.0.2.2
vagrant@ubuntu-bionic:~$

**Comment by michaelshmitty** [comment]
Ubuntu 18.04 LTS will be supported for 5 years, as any LTS version.
At present there is no need to upgrade the build machine for mr fusion.
Thanks for your interest and input. Have fun with MiSTer.
