### ISSUE TITLE
update mame file to _Arcade sends to scripts _Arcade instead

### ISSUE THREAD

**Issue by ThetaX55** [MiSTer-devel/mr-fusion#11]
Im new to update all. I updated and made it send to _Arcade. games didn't boot.
I ended up finding the roms in a _Arcade folder in the script folder.

**Comment by michaelshmitty** [comment]
Wrong repo. This has nothing to do with Mr. Fusion or even the official MiSTer project. I suggest you contact the author of the update_all script.
