### ISSUE TITLE
Build & clean scripts broken.

### ISSUE THREAD

**Issue by ArcadeHustle** [MiSTer-devel/mr-fusion#12]
https://github.com/MiSTer-devel/mr-fusion/blob/master/scripts/build.sh#L19
https://github.com/MiSTer-devel/mr-fusion/blob/master/scripts/clean.sh#L19

errors out on "cd ~/buildroot" 

Where is buildroot? 

https://buildroot.org/downloads/manual/manual.html#_complying_with_open_source_licenses
https://buildroot.org/downloads/manual/manual.html#legal-info-buildroot

**Comment by michaelshmitty** [comment]
It's there when you provision the VM using Vagrant.
https://github.com/MiSTer-devel/mr-fusion/blob/master/Vagrantfile#L130

Not sure what the issue is exactly, nor what you're implying with the referenced material. Either elaborate, file a more complete error report or propose a PR with a fix.
Thanks!

**Comment by birdybro** [comment]
@sorgelig I suggest this thread be closed and locked, the opening poster is a known troll and is not making a serious request.

**Comment by michaelshmitty** [comment]
That won't be necessary @birdybro , I will resolve the issue.
@ArcadeHustle this will be addressed as soon as possible. Thanks for filing.

**Comment by ArcadeHustle** [comment]
Thanks @michaelshmitty, I was indeed not using Vagrant.

**Comment by michaelshmitty** [comment]
@ArcadeHustle even so, you may still have a point even if you're not using vagrant. We are releasing binary versions of mr-fusion and after carefully reading the material you have linked, it may be the intention of buildroot to developers to have the buildroot source and config included in this repo. I will take care of that as soon as possible. Thanks again for bringing attention to this.

**Comment by mikegreiling** [comment]
Thank you very much for this 💯
