### ISSUE TITLE
[Feature Request] ath9k_htc driver?

### ISSUE THREAD

**Issue by yanfali** [MiSTer-devel/mr-fusion#14]
Hello, I have a Atheros 9271 usb based wifi card, and I tested it under Raspberry Pi. Any chance you could include this driver on the next release please?

Thanks

Yan

**Comment by yanfali** [comment]
https://wireless.wiki.kernel.org/en/users/Drivers/ath9k_htc it's a stock kernel driver. It might also need a firmware blob.

**Comment by michaelshmitty** [comment]
Hi, thanks for your message!

This is not the right repository for your request. Please submit your issue on the [MiSTer Linux Kernel repository](https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/issues).
