### ISSUE TITLE
Request: Update to latest sd-installer release and add downloader.sh script

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/mr-fusion#15]
The current workflow for the user adds an unnecessary sd-installer download to update the linux image so it's a bit redundant, could you update the release? I am not totally sure if that entails more than just modifying the one line which copies the sd-installer otherwise I would have submitted a PR myself.

Also, many users are being guided to use the new downloader.sh script now from https://github.com/MiSTer-devel/Downloader_MiSTer - if that could be added that would be appreciated. If it is only your goal to have scripts included that are already present in sd-installer I will ask that it be added there to that image instead.

Thanks!

**Comment by michaelshmitty** [comment]
> The current workflow for the user adds an unnecessary sd-installer download to update the linux image so it's a bit redundant, could you update the release? I am not totally sure if that entails more than just modifying the one line which copies the sd-installer otherwise I would have submitted a PR myself.
> 
Thanks for letting me know there's a Linux image update. That's always a good time to release an updated mr-fusion image. It is more than just changing the line, I need to create a new image and create a new release, but I'm used to it by now so it won't take much effort. More below...

> Also, many users are being guided to use the new downloader.sh script now from https://github.com/MiSTer-devel/Downloader_MiSTer - if that could be added that would be appreciated. If it is only your goal to have scripts included that are already present in sd-installer I will ask that it be added there to that image instead.
> 
This! Actually I was waiting on creating a new mr-fusion image until they included the new downloader script upstream. I have opened [an issue for this](https://github.com/MiSTer-devel/Main_MiSTer/issues/483) upstream last November (you have liked it).
In that issue I mention it's better to replace the old downloader.sh script with the new one upstream in the official release. That way the old one goes away at the same time and I don't have to monkey patch the MiSTer release that goes into the mr-fusion image.
So you're right about that, my goal for mr-fusion is to interfere as little as possible with the MiSTer release. So if you don't mind giving them a little nudge there, that would be great. Let me know here when a new MiSTer release includes the new downloader script and I'll get a new mr-fusion release out asap!
> Thanks!
You're very welcome!

**Comment by birdybro** [comment]
It's been so long I forgot! LOL

Thanks for responding so quickly like you always do.

**Comment by michaelshmitty** [comment]
I decided to release [a version of mr-fusion](https://github.com/MiSTer-devel/mr-fusion/releases/tag/v2.4) with the new downloader script bundled until they include it in the next upstream Linux for MiSTer release. It's not as confusing as I initially thought because the old script is called `update` and the new one is called `downloader`.
