### ISSUE TITLE
update.sh script tells you it's located in the downloader github

### ISSUE THREAD

**Issue by arromdee** [MiSTer-devel/mr-fusion#16]
~~update.sh contains these lines:~~
```
# You can download the latest version of this tool from:
# https://github.com/MiSTer-devel/Downloader_MiSTer
```

~~Needless to say, no update.sh can be found there because of the name change.  It doesn't mention a name change either, so users have to be confused, guess, and compare files.~~

~~The file I found at https://github.com/MiSTer-devel/Updater_script_MiSTer does produce a warning that mentions the name change, but the one I got in Mister Fusion doesn't contain this warning.~~

(Reopened in https://github.com/MiSTer-devel/SD-Installer-Win64_MiSTer/)

**Comment by birdybro** [comment]
This is because sorgelig renamed downloader.sh to update.sh when distributing the installer release. Update.sh from the latest release is the same as downloader.sh as of 20220413.

**Comment by arromdee** [comment]
Moved to  https://github.com/MiSTer-devel/SD-Installer-Win64_MiSTer/
