### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by MJoergen** [MiSTer-devel/mr-fusion#17]
Hi, I'm using Ubuntu 20.04.5 LTS, and I get the following errors:

```
Installed the plugin 'vagrant-vbguest (0.30.0)'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /home/mfj/git/PRIVATE/MiSTer-devel/mr-fusion/scripts/S99install-mister.sh must exist

Vagrant:
* Unknown configuration section 'disksize'.
```

The first error (about missing file) seems to be a problem with mixed case. I change `mister` to `MiSTer` in line 145 in Vagrantfile and the problem is now fixed.

However, the second error (about disksize) still persists.

How can I proceed?

**Comment by michaelshmitty** [comment]
> Hi, I'm using Ubuntu 20.04.5 LTS, and I get the following errors:
> 
> ```
> Installed the plugin 'vagrant-vbguest (0.30.0)'!
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> File provisioner:
> * File upload source file /home/mfj/git/PRIVATE/MiSTer-devel/mr-fusion/scripts/S99install-mister.sh must exist
> 
> Vagrant:
> * Unknown configuration section 'disksize'.
> ```
> 
> The first error (about missing file) seems to be a problem with mixed case. I change `mister` to `MiSTer` in line 145 in Vagrantfile and the problem is now fixed.

Thanks for noticing this! I've mainly used this on MacOS which unfortunately has a case insensitive filesystem. I'll double check and make sure provisioning the VM on a Linux host works as well in the future.

> 
> However, the second error (about disksize) still persists.
> 
> How can I proceed?

You need to install [the disksize plugin](https://github.com/sprotheroe/vagrant-disksize). For some reason and unless I'm missing something Vagrant doesn't support setting an arbitrary disk size in the Vagrantfile. The plugin gives a provider agnostic way to specify the VM disk space.
I'll update the documentation to mention installing this plugin. Thanks!
