### ISSUE TITLE
[Feature Request] NFS script

### ISSUE THREAD

**Issue by osaeed18** [MiSTer-devel/mr-fusion#19]
Can this nfs script be added to the Fusion Install? https://github.com/basvandewiel/misternfs
NFS is now enabled in the latest linux kernel.

**Comment by michaelshmitty** [comment]
Thanks for submitting this request!

I see you have already closed it, but I'll respond anyway for future reference:
Mr. Fusion tries not to include additional scripts in the installer apart from the ones that are included in the upstream [MiSTer release](https://github.com/MiSTer-devel/Main_MiSTer/tree/master/releases). So if you want the NFS scripts to become part of a default MiSTer install, please [open a request](https://github.com/MiSTer-devel/Main_MiSTer/issues) in the [Main_MiSTer](https://github.com/MiSTer-devel/Main_MiSTer) repository.

That said, Mr. Fusion does support adding additional scripts during an install. But you'll have to add them yourself. See [Adding more scripts](https://github.com/MiSTer-devel/mr-fusion#adding-more-scripts) for more details.
