### ISSUE TITLE
Bundling uboot config with MAC

### ISSUE THREAD

**Issue by wizzomafizzo** [MiSTer-devel/mr-fusion#20]
Hi. I was wondering what you might think about having Mr fusion by default generate a u-boot.txt with a newly generated random ethernet MAC address configured?

I think this could potentially be a good spot, since it couldn't be shipped statically in the release image and is a poor user experience when done with a script

I guess there is a risk to accept with a MAC collision. But it would fix a long standing and pretty critical issue with mister where multiple misters plugged into the same network will simply break all of them

**Comment by michaelshmitty** [comment]
Thanks for your suggestion! That could be a good fit for mr-fusion to take care of. I'll look into it and discuss with others.

**Comment by wizzomafizzo** [comment]
Hey thanks very much for considering it! I'd be happy to put in a pull request if you end up ok-ing it but don't have time. Though I'm also happy to do less work :smile:

**Comment by michaelshmitty** [comment]
> Hey thanks very much for considering it! I'd be happy to put in a pull request if you end up ok-ing it but don't have time. Though I'm also happy to do less work 😄

Sure, your PR would be very welcome! I'll gather some feedback on the idea and get back to you. Thanks again!

**Comment by michaelshmitty** [comment]
@wizzomafizzo I've got positive community feedback, it's a good idea and mr-fusion is a good fit to apply this change. I'm a bit busy these days, but I welcome a PR and happily review it!
