### ISSUE TITLE
No power on the USB port using Mr. Fusion ver 2.9

### ISSUE THREAD

**Issue by soniccd123** [MiSTer-devel/mr-fusion#23]
So, I bought a new DE-10 Nano in January/2024, got it today and started testing, deployed Mr. Fusion 2.9 and it worked alright, but the USB Port in which USB OTG adapters are connected would not work. I tested a lot of Hubs and adapter and any of them worked. Tested the port voltage and it was always 0V across the power rail. Tried some diferent SD cards as said in some posts on Mister FPGA Forum with no success, tried changing the dip switches without success, tried reseting the De-10 Nano with no sign of life on the USB port.

What worked was when I tried version 2.5, it worked the first try. Tried again installing, this time doing a manual installation as in this link: https://github.com/MiSTer-devel/Wiki_MiSTer/wiki/Setup-Guide, using the latest version of Mister SD card Utility (20231108 as of today) and the latest firmware (20240110 as of today) and it worked flawlessly. 

When I got it working, I was using the stock power supply that comes with the DE-10, without a USB HUB or IO board, just a generic USB OTG adapter, so, it doesn't seem to be a power problem.

I just like to you guys to know that this is happening. If you want I may have equipment necessary to run diagnostic tests to help findout what is the problem, but as a newbie on the Mister scene, would need some help to know which ones are needed for debugging this.

**Comment by soniccd123** [comment]
Okay, i will close this issue, i'm actually quite stupid, on further testing it was indeed a power problem, using a 3A 5V power supply solved the USB instability issue. The different versions of Mister Fusion and setups really had an impact in the USB stability using a 2A power supply, but this is obviously not a problem when using one with the correct ratings

**Comment by michaelshmitty** [comment]
Sorry to get back to this so late, the notification got lost in the mail. Thanks for posting this here anyway, glad you got it working. Yes, underpowering your setup potentially causing brownouts can cause unexpected issues. It's not unlikely that different software versions have fluctuating power demands which may just push the whole system over the limit, causing problems. It's a good idea to upgrade the stock power supply as you did. Good luck!
