### ISSUE TITLE
Trouble with OTG - Wireless keyboard

### ISSUE THREAD

**Issue by okwatts** [MiSTer-devel/mr-fusion#24]
I just tried to update from an old pre Sept 2021 to the latest and I was told  I needed a later linux image. I downloaded the latest SD Mr Fusion and installed on a new SD card. Now my wireless keyboard does not respond. This works fine with the old version. What am I doing wrong?? I am using the micro OTG dongle.

**Comment by okwatts** [comment]
I spoke too soon after having the keyboard working, I did an update and now after rebooting the keyboard does not respond. There is something flaky going on here.

**Comment by michaelshmitty** [comment]
Hi, thanks for opening this issue. This project is for the mr-fusion installer for MiSTer and not MiSTer itself. Please open an issue at the [main MiSTer project](https://github.com/MiSTer-devel/Main_MiSTer/issues) or refer to the mister forums or discord for support.
That said, good power is important so it’s good you use a 4A power supply to rule out possible brownout issues. Good luck!
