### ISSUE TITLE
Keep log file of the MiSTer installation process

### ISSUE THREAD

**Issue by michaelshmitty** [MiSTer-devel/mr-fusion#3]
Log stdout and stderr to a log file in tmpfs. Copy the logfile to MiSTer_Data before reboot.

**Comment by theypsilon** [comment]
Probably you know how to do it already.

But in case you would like to see a working solution, I wrote this code for my projects. You may use if you want:

```bash

enable_global_log() {
    exec >  >(tee -ia ${GLOG_TEMP})
    exec 2> >(tee -ia ${GLOG_TEMP} >&2)
}

disable_global_log() {
    exec 1>&6 ; exec 2>&7
}


initialize_global_log() {
    rm ${GLOG_TEMP} 2> /dev/null || true
    exec 6>&1 ; exec 7>&2 # Saving stdout and stderr
    enable_global_log
    trap "mv ${GLOG_TEMP} ${GLOG_PATH}" EXIT
}

initialize_global_log

# running initialize_global_log only would be enough, if there is no need to restore stdout, and stderr
```

**Comment by michaelshmitty** [comment]
I only thought of using ```tee```, I had not given it more thought than that. This is a great suggestion, thanks!

**Comment by michaelshmitty** [comment]
Closing this. Given there are currently zero reported issues with the mr-fusion installation process that would warrant the need to backtrace a problem, I see no merit in implementing this feature for now.
If it ever becomes necessary, we can revisit this.
