### ISSUE TITLE
Splash over 15kHz

### ISSUE THREAD

**Issue by mortaca** [MiSTer-devel/mr-fusion#4]
Hi, I'm making a fork of you image pre-configured for a 15kHz output over the IO board, I can add the .ini inside release.rar to see at 240p and composite sync after the SD expansion but I can't see the spash screen during the installation because on first boot the system don't read .ini files, how can I configure the bootloader to run on a 240p from startup?

Best regards.

**Comment by michaelshmitty** [comment]
Hello!

I appreciate and understand what you're trying to accomplish. Unfortunately Mr. Fusion only supports output over HDMI. MiSTer is way more advanced and supports multiple output variants. Mr. Fusion does not use MiSTer to boot. It uses sample code from the Intel DE-10 nano Linux framebuffer project just to get a simple framebuffer on screen.

While packaging a custom ini file that supports 15 kHz output for MiSTer out of the box will do what you expect when MiSTer boots, it will not be used by Mr. Fusion.

The bootloader is not what makes the video output possible. It only supports output over a serial connection. The bootloader loads a bitstream that reconfigures the fpga to have HDMI capabilities. Linux then is able to open a framebuffer device to that HDMI output.

So what you want will only be possible if someone can create a bitstream (core) that enables HDMI and 15 kHz output (like the main MiSTer core does).

**Comment by mortaca** [comment]
Perfectly explained, thank you very much for the clarification.
