### ISSUE TITLE
Request: make TGFX16-CD folder upon install

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/mr-fusion#5]
Many unofficial scripts, guides, etc... Refer to a TGFX16-CD folder to be used, and as such it could be considered "community standard". Currently this folder is missing in any official method of setting up the MicroSD. It would be relatively harmless to add this in the folder generation step of install. 

Thanks!

**Comment by michaelshmitty** [comment]
@birdybro thanks for reporting this. The mr-fusion installer is not responsible for creating the core subfolders in the games folder. This is done by the [official MiSTer Updater script](https://github.com/MiSTer-devel/Updater_script_MiSTer). Feel free to open an issue there.

**Comment by birdybro** [comment]
Ah, just realized that. I didn't even notice. I already let theypsilon know for his update-all script, so I will move this over there too.
