### ISSUE TITLE
Request: detect from root of drive and copy wpa_supplicant if found

### ISSUE THREAD

**Issue by versechoruscurse** [MiSTer-devel/mr-fusion#7]
I wondered if there was a way Mr Fusion could use wpa_supplicant.conf if it was found in the root folder of the SD Card before first boot?

**Comment by michaelshmitty** [comment]
Interesting idea.
If that's what the wifi.sh script does then it should be possible to have Mr Fusion copy a wpa_supplicant.conf file that you put on the SD card somewhere to the right location after setting up MiSTer.
Just like it currently does with any additional scripts you add.
I'll look into this. Thanks for the request.

**Comment by michaelshmitty** [comment]
I've looked into it and it's possible. In fact I think it would make sense to expand this to the ``samba.sh`` file as well.
I assume the reason for your request is to avoid having to connect a keyboard to the MiSTer at all after initial installation, is that right @versechoruscurse ?
If this new functionality is implemented, you have everything you need to start using your MiSTer without having to connect a keyboard: Ethernet connectivity is supported automatically, an initial wpa_supplicant.conf will be copied if present to enable wifi and an initial samba.sh script will enable (custom) shares to be exposed over the network.
I'll work on this as soon as I can and release version 2.2.

**Comment by versechoruscurse** [comment]
That's exactly my thinking. Thanks so much for this!
