### ISSUE TITLE
Onboard Ethernet MAC address override in "linux/uboot.img" prevents DHCP lease

### ISSUE THREAD

**Issue by alexanderupton** [MiSTer-devel/mr-fusion#8]
Seems that the boot image has a hard coded "ethaddr=02:03:04:05:06:07" definition in "linux/uboot.img" that prevents a successful DHCP lease. Please consider removing this "ethaddr" statement so users can utilize the onboard Ethernet controller instead of Wifi.

Thank you

**Comment by michaelshmitty** [comment]
Hi, thanks for opening this issue.

Mr. Fusion does not require / use networking and nothing Mr. Fusion provides persists after it has installed MiSTer and reboots, not even its bootloader.
Maybe you're referring to the bootloader MiSTer uses?
You may want to report this on the [main MiSTer project](https://github.com/MiSTer-devel/Main_MiSTer/issues).

Kind regards.
